//AUTHENTICATION
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGNOUT = "SIGNOUT";

//MOVIES
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";
export const GET_GENRES_ERROR = "GET_GENRES_ERROR";

export const FAVOURITE_CARD_SUCCESS = "FAVOURITE_CARD_SUCCESS";
export const FAVOURITE_CARD_ERROR = "FAVOURITE_CARD_ERROR";
